spring.application.name=springboot-template
server.port=${SERVER_PORT:8081}

spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:platform_template}
spring.data.mongodb.auto-index-creation=true

logging.level.com.springboot_template.springboot_template=INFO
