spring.application.name=springboot-template
server.port=${SERVER_PORT:8081}

spring.data.mongodb.uri=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=${MONGODB_AUTH_DATABASE}&directConnection=true
spring.data.mongodb.auto-index-creation=true

logging.level.com.springboot_template.springboot_template=INFO
